sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.m2

notifications:
  email: false

before_install:
  - export TALEND_COMMIT_MSG=$TRAVIS_COMMIT_MESSAGE
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TALEND_COMMIT_MSG="$(git log --format=%B -n 1 $TRAVIS_PULL_REQUEST_SHA)"; fi
  # Configure git
  - .travis/before_install.sh

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js:
        - '10'
      env:
        - NAME=demo E2E cypress
      before_script:
        - yarn global add surge
        - yarn install
        - yarn test:demo
        - if [ -z "$GH_TOKEN" ]; then echo "No credentials, this PR must be from a fork. Demo skipped."; travis_terminate 0; fi
        - .travis/after_success_static.sh
        - .travis/after_success_demo.sh
        - .travis/after_success_deploy.sh
        - CYPRESS_baseUrl=$TRAVIS_PULL_REQUEST.talend.surge.sh/components yarn 2e2
      script:
        - .travis/after_success_e2e.sh

branches:
  only:
    - master
